### ISSUE TITLE
Add link to the container-registry plugin-install page

### ISSUE THREAD

**Issue by Ms-Amara** [ibm-cloud-docs/Registry#428]
Add a link on page https://cloud.ibm.com/docs/cli?topic=cli-install-ibmcloud-cli for easy traversal to the container-registry plugin-install page https://www.ibm.com/docs/en/filenet-p8-platform/5.5.x?topic=images-getting-access-container-cloud-roks

**Comment by SueGraham** [comment]
@Ms-Amara 

Thanks for your feedback.

Please can I confirm where you want a link because the link that you give isn't for installing IBM Cloud Container Registry.

So, I think you want a link from this page: 
https://cloud.ibm.com/docs/cli?topic=cli-install-ibmcloud-cli

to this page:
https://cloud.ibm.com/docs/cli?topic=cli-install-devtools-manually

is that right?


Regards

Sue

**Comment by Ms-Amara** [comment]
Hi Sue, 

Thanks for picking this up. 

TBH, the command on this page helped me - https://www.ibm.com/docs/en/filenet-p8-platform/5.5.x?topic=images-getting-access-container-cloud-roks. The plugin link didn't quite help. 

Therefore, I as part of the docs, I've added the command on the page itself - the exact command is: 
ibmcloud plugin install container-registry -r 'IBM Cloud'

**Comment by SueGraham** [comment]
@Ms-Amara  HI,

You don't need to use the `-r 'IBM Cloud'` because that's the default anyway.

so this command should be OK:
`ibmcloud plugin install container-registry `

https://cloud.ibm.com/docs/cli?topic=cli-ibmcloud_commands_settings#ibmcloud_plugin_install

![image](https://user-images.githubusercontent.com/26408909/158548089-3252818b-f22c-4987-8f0b-f42abdcd14e9.png)

I can't update the page itself because it doesn't belong to me, but I'll create PR for it.

Regards

Sue

**Comment by SueGraham** [comment]
Updated in prod: https://cloud.ibm.com/docs/cli?topic=cli-install-ibmcloud-cli
