### ISSUE TITLE
ibmcloud cr images --include-ibm

### ISSUE THREAD

**Issue by tivolinick** [ibm-cloud-docs/Registry#438]
This doesn't list any of the turbonomic images under the cpopen namespace. Doc needs to describe how to do that

**Comment by bainsy88** [comment]
@tivolinick `--ibm-images` is designed to show images that can be used as standalone images and therefore have been added to a specific namespace. 

The general model for images in `cpopen` is that those images from part of a CloudPak and therefore are installed and versioned at the CloudPak level meaning that direct use of the images is not expected which is why we do not document or have a separate flag for listing them
